import Link from "next/link"
import { ArrowRight, Check, FileCheck2, Fingerprint, ScanLine, ShieldCheck, Sparkles } from "lucide-react"
import { BrandMark } from "@/components/brand-mark"
import { ReceiptPreview } from "@/components/receipts/receipt-preview"
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { EMPTY_RECEIPT_VIEW_MODEL } from "@/lib/receipt-types"

const demoReceipt = { ...EMPTY_RECEIPT_VIEW_MODEL, id: "demo", archiveId: "TS-2026-000184", hasOriginalSource: true, status: "final" as const, merchant: { ...EMPTY_RECEIPT_VIEW_MODEL.merchant, name: "Kijani Market", address: "Ngong Road · Nairobi", contacts: "+254 700 000 000" }, sourceNumber: "KM-78420", issuedAt: "2026-08-24T08:42:00.000Z", lines: [{ id: "1", description: "Kenyan coffee beans", quantity: "2", unitPriceMinor: 85000, discountMinor: 0, taxMinor: 0, totalMinor: 170000 }, { id: "2", description: "Canvas market bag", quantity: "1", unitPriceMinor: 45000, discountMinor: 0, taxMinor: 0, totalMinor: 45000 }], subtotalMinor: 215000, taxMinor: 34400, totalMinor: 249400, paymentMethod: "M-PESA", paymentReference: "QH42•••7M" }

export default function Home() {
  return <main className="min-h-screen overflow-hidden">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><BrandMark/><div className="flex items-center gap-2"><Link href="/sign-in" className={buttonVariants({ variant: "ghost" })}>Sign in</Link><Link href="/sign-up" className={buttonVariants()}>Start tracing <ArrowRight data-icon="inline-end" /></Link></div></nav>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-14 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pt-20"><div><p className="ledger-label mb-6 flex items-center gap-2 text-accent"><span className="h-px w-8 bg-accent" /> From paper slip to traceable record</p><h1 className="max-w-3xl text-5xl font-semibold leading-[.95] tracking-[-.065em] sm:text-7xl lg:text-[5.7rem]">Paper fades.<br/><span className="text-accent">Evidence shouldn’t.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground sm:text-xl">Scan any receipt, review every AI suggestion against the original, then preserve a trustworthy digital copy with a complete audit trail.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/sign-up" className={cn(buttonVariants({ size: "lg" }), "h-12 px-6")}>Create your workspace <ArrowRight data-icon="inline-end" /></Link><Link href="#how-it-works" className={cn(buttonVariants({ variant: "outline", size: "lg" }), "h-12 bg-background/70 px-6")}>See how review works</Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 font-mono text-xs text-muted-foreground">{["AI never auto-saves","Private source storage","Immutable final copies"].map((item)=><span key={item} className="flex items-center gap-2"><Check className="size-3.5 text-accent"/>{item}</span>)}</div></div><div className="relative min-h-[590px]"><div className="absolute inset-x-0 top-12 mx-auto h-[440px] max-w-[480px] rotate-3 border border-border bg-card/55"/><ReceiptPreview receipt={demoReceipt} className="relative z-10 -rotate-2 transition-transform duration-500 hover:rotate-0"/><div className="absolute bottom-3 left-0 z-20 max-w-[230px] border border-border bg-[#1f1d19] p-4 text-[#f7f1e7] shadow-2xl"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-orange-400">Source check</p><p className="mt-2 text-sm font-medium">Total matched the printed source</p><div className="mt-3 flex items-center gap-2 font-mono text-xs text-white/55"><ShieldCheck className="size-4 text-emerald-400"/> 99% confidence</div></div></div></section>
    <section id="how-it-works" className="border-y border-border bg-[#201e1a] text-[#f5efe5]"><div className="mx-auto grid max-w-7xl lg:grid-cols-4">{[[ScanLine,"01 / Capture","Camera, drag-and-drop, or PDF. The original stays private and attached."],[Sparkles,"02 / Extract","AI proposes fields with confidence and the exact source text behind each one."],[FileCheck2,"03 / Review","Apply safe suggestions, correct mismatches, and undo. Nothing saves itself."],[Fingerprint,"04 / Preserve","Finalize an immutable record, print it, or export thermal and A4 PDFs."]].map(([Icon,label,copy],index)=>{const FeatureIcon=Icon as typeof ScanLine;return <div key={label as string} className={cn("min-h-64 border-white/10 p-7",index<3&&"border-b lg:border-b-0 lg:border-r")}><FeatureIcon className="size-7 text-orange-400"/><p className="mt-10 font-mono text-xs uppercase tracking-[.18em] text-white/55">{label as string}</p><p className="mt-3 max-w-xs text-lg leading-7">{copy as string}</p></div>})}</div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="ledger-label text-accent">Built for accountable teams</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">One source.<br/>Every decision visible.</h2></div><div className="grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-2">{[["Confidence by field","Low-confidence and mismatched money stays unchecked until a person reviews it."],["Workspace oversight","Owners and admins can oversee projects, receipts, exports, invitations, and audit activity."],["Ten honest presets","Change the paper design without changing reviewed receipt data or inventing merchant identity."],["Support without mutation","Audited 15-minute impersonation is read-only, visibly bannered, and records raw-source access."]].map(([title,copy])=><div key={title} className="bg-card p-7"><p className="text-lg font-semibold">{title}</p><p className="mt-3 leading-7 text-muted-foreground">{copy}</p></div>)}</div></div></section>
    <footer className="border-t border-border px-5 py-7 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><BrandMark/><p className="font-mono text-xs text-muted-foreground">DIGITIZED COPIES · SOURCE-BACKED · HUMAN-REVIEWED</p></div></footer>
  </main>
}
