"use client"
/* eslint-disable @next/next/no-location-assign-relative-destination -- the auth cookie changes before leaving the admin identity */
import { useState } from "react"
import { useRouter } from "next/navigation"
import { Ban, Eye, RotateCcw, ShieldOff } from "lucide-react"
import { toast } from "sonner"
import { authClient } from "@/lib/auth-client"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Textarea } from "@/components/ui/textarea"

export function UserOperations({userId,banned}:{userId:string;banned:boolean}){const router=useRouter();const[reason,setReason]=useState("");const[open,setOpen]=useState(false);async function toggleBan(){const result=banned?await authClient.admin.unbanUser({userId}):await authClient.admin.banUser({userId,banReason:"Suspended by TraceSlip platform operations"});if(result.error)toast.error(result.error.message??"Operation failed");else{toast.success(banned?"Account restored":"Account suspended");router.refresh()}}async function revoke(){const result=await authClient.admin.revokeUserSessions({userId});if(result.error)toast.error(result.error.message??"Unable to revoke sessions");else toast.success("Sessions revoked")}async function impersonate(){if(reason.trim().length<10)return;const recorded=await fetch("/api/platform/impersonation/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId,reason})});if(!recorded.ok){toast.error((await recorded.json()).error);return}const result=await authClient.admin.impersonateUser({userId});if(result.error){toast.error(result.error.message??"Unable to start support view");return}window.location.assign("/app")}return <div className="flex flex-wrap justify-end gap-1"><Button size="sm" variant="ghost" onClick={toggleBan}>{banned?<RotateCcw/>:<Ban/>}{banned?"Restore":"Suspend"}</Button><Button size="sm" variant="ghost" onClick={revoke}><ShieldOff/>Revoke sessions</Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button size="sm" variant="outline"/>}><Eye/>Support view</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Start read-only support view?</DialogTitle><DialogDescription>This audited session expires in 15 minutes. All receipt and workspace mutations are disabled, and raw source access is logged explicitly.</DialogDescription></DialogHeader><Textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Required support reason (at least 10 characters)"/><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={impersonate} disabled={reason.trim().length<10}>Start support view</Button></DialogFooter></DialogContent></Dialog></div>}
export function WorkspaceOperations({organizationId,suspended}:{organizationId:string;suspended:boolean}){const router=useRouter();async function toggle(){const response=await fetch("/api/platform/workspaces/suspension",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,suspended:!suspended,reason:"Platform operations review"})});if(!response.ok)toast.error((await response.json()).error);else{toast.success(suspended?"Workspace restored":"Workspace suspended");router.refresh()}}return <Button size="sm" variant="ghost" onClick={toggle}>{suspended?<RotateCcw/>:<Ban/>}{suspended?"Restore":"Suspend"}</Button>}
