import { and, eq } from "drizzle-orm"
import { NextResponse } from "next/server"
import { z } from "zod"
import { auditEvents, members, projectMembers } from "@/db/schema"
import { assertMutableSession, getProjectAccess, getRequestSession } from "@/lib/authorization"
import { canManageProject } from "@/lib/permissions"
import { db } from "@/lib/db"
import { PROJECT_ROLES } from "@/lib/receipt-types"
const schema=z.object({userId:z.string(),role:z.enum(PROJECT_ROLES)})
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const session=await getRequestSession();if(!session)return NextResponse.json({error:"Resource not found"},{status:404});assertMutableSession(session);const{id}=await params;const input=schema.parse(await request.json());const access=await getProjectAccess(session.user.id,id);if(!canManageProject(access))return NextResponse.json({error:"Resource not found"},{status:404});const[target]=await db.select({id:members.id}).from(members).where(and(eq(members.organizationId,access.organizationId),eq(members.userId,input.userId))).limit(1);if(!target)return NextResponse.json({error:"Choose an existing workspace member"},{status:400});await db.transaction(async tx=>{await tx.insert(projectMembers).values({projectId:id,organizationId:access.organizationId,userId:input.userId,role:input.role}).onConflictDoUpdate({target:[projectMembers.projectId,projectMembers.userId],set:{role:input.role,organizationId:access.organizationId}});await tx.insert(auditEvents).values({organizationId:access.organizationId,actorUserId:session.user.id,effectiveUserId:session.user.id,action:"project.member_assigned",entityType:"project",entityId:id,metadata:{userId:input.userId,role:input.role}})});return NextResponse.json({ok:true})}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Invalid project role"},{status:400});return NextResponse.json({error:"Resource not found"},{status:404})}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{const session=await getRequestSession();if(!session)return NextResponse.json({error:"Resource not found"},{status:404});assertMutableSession(session);const{id}=await params;const input=z.object({userId:z.string()}).parse(await request.json());const access=await getProjectAccess(session.user.id,id);if(!canManageProject(access))return NextResponse.json({error:"Resource not found"},{status:404});await db.transaction(async tx=>{await tx.delete(projectMembers).where(and(eq(projectMembers.projectId,id),eq(projectMembers.userId,input.userId)));await tx.insert(auditEvents).values({organizationId:access.organizationId,actorUserId:session.user.id,effectiveUserId:session.user.id,action:"project.member_removed",entityType:"project",entityId:id,metadata:{userId:input.userId}})});return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"Resource not found"},{status:404})}}
