import { eq } from "drizzle-orm"
import { NextResponse } from "next/server"
import { z } from "zod"
import { auditEvents, invitations, organizations, users } from "@/db/schema"
import { db } from "@/lib/db"
import { sendTransactionalEmail } from "@/lib/email"
import { requirePlatformAdmin } from "@/lib/platform-authorization"
const schema=z.object({invitationId:z.string()})
export async function POST(request:Request){try{const session=await requirePlatformAdmin();const{invitationId}=schema.parse(await request.json());const[invitation]=await db.select({id:invitations.id,email:invitations.email,status:invitations.status,organizationId:invitations.organizationId,organizationName:organizations.name,inviterName:users.name}).from(invitations).innerJoin(organizations,eq(organizations.id,invitations.organizationId)).innerJoin(users,eq(users.id,invitations.inviterId)).where(eq(invitations.id,invitationId)).limit(1);if(!invitation||invitation.status!=="pending")return NextResponse.json({error:"Resource not found"},{status:404});const expiresAt=new Date(Date.now()+72*60*60*1000);await db.update(invitations).set({expiresAt}).where(eq(invitations.id,invitation.id));const defaultAppUrl=process.env.NODE_ENV==="production"?"https://blackielabs.com":"http://localhost:3000";const appUrl=process.env.NEXT_PUBLIC_APP_URL??process.env.BETTER_AUTH_URL??defaultAppUrl;await sendTransactionalEmail({to:invitation.email,subject:`Join ${invitation.organizationName} on TraceSlip`,preview:`Invitation to ${invitation.organizationName}`,heading:`Join ${invitation.organizationName}`,message:`${invitation.inviterName} invited you to collaborate. Sign in with this exact verified email to accept.`,actionLabel:"Review invitation",actionUrl:`${appUrl}/accept-invitation?id=${encodeURIComponent(invitation.id)}`,footnote:"This resent invitation expires after 72 hours."});await db.insert(auditEvents).values({organizationId:invitation.organizationId,actorUserId:session.user.id,effectiveUserId:session.user.id,action:"platform.invitation_resent",entityType:"invitation",entityId:invitation.id,metadata:{email:invitation.email,expiresAt:expiresAt.toISOString()}});return NextResponse.json({ok:true})}catch(error){console.error("invitation resend failed",error);return NextResponse.json({error:"Unable to resend invitation"},{status:400})}}
